-- Knowledge Foyer v1.0 (Phase 9). Identity tables come from
-- server/identity.sql, applied first by run.js, so created_by can
-- reference users. Everything here is idempotent — run.js reapplies the
-- schema on every start.

CREATE TABLE IF NOT EXISTS articles (
    id         integer PRIMARY KEY,
    created_by integer REFERENCES users(id),
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS article_editions (
    id         integer PRIMARY KEY,
    article_id integer NOT NULL REFERENCES articles(id),
    title      text NOT NULL DEFAULT '',
    body       text NOT NULL DEFAULT '',
    revision   integer NOT NULL DEFAULT 0
);

-- Phase 9: the publish workflow. status is a plain column — publish is a
-- status write through the ordinary Wire, per RESOLVED (publish is a
-- status write).
ALTER TABLE article_editions ADD COLUMN IF NOT EXISTS status text NOT NULL DEFAULT 'draft';
ALTER TABLE article_editions ADD COLUMN IF NOT EXISTS published_at timestamptz;

-- Next editions come from the composer; give them server-assigned ids
-- without disturbing the seeded 1/2.
CREATE SEQUENCE IF NOT EXISTS article_editions_id_seq OWNED BY article_editions.id;
-- Never move the sequence BACKWARDS: this reapplies on every start, and
-- if rows at the top were deleted, a plain MAX(id) would rewind the
-- sequence and re-mint deleted ids (eventually colliding with a live
-- row). last_value is the floor.
SELECT setval('article_editions_id_seq', GREATEST(
    100,
    (SELECT last_value FROM article_editions_id_seq),
    (SELECT COALESCE(MAX(id), 0) FROM article_editions)));
ALTER TABLE article_editions ALTER COLUMN id SET DEFAULT nextval('article_editions_id_seq');

-- Published editions are immutable at the schema, per the RESOLVED entry
-- of that name: integrity is the app's SQL, exactly like its FKs. The
-- one-way door: publishing is an UPDATE on a still-draft row (which this
-- trigger also timestamps); once status is 'published', UPDATE and DELETE
-- are rejected — owner included. The framework answers the rejection as a
-- 400 carrying this message.
CREATE OR REPLACE FUNCTION kf_published_immutable() RETURNS trigger AS $$
BEGIN
    IF OLD.status = 'published' THEN
        RAISE EXCEPTION 'published editions are immutable — corrections go in the next edition';
    END IF;
    IF TG_OP = 'UPDATE' AND NEW.status = 'published' AND OLD.status = 'draft' THEN
        NEW.published_at := now();
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS kf_published_immutable ON article_editions;
CREATE TRIGGER kf_published_immutable
    BEFORE UPDATE OR DELETE ON article_editions
    FOR EACH ROW EXECUTE FUNCTION kf_published_immutable();

-- One draft at a time per article: the draft IS the next edition in
-- progress; a second "Start next edition" press is a database rejection
-- answered 400, same doctrine as the immutability trigger. (A database
-- holding duplicate drafts fails here at startup — resolve by hand;
-- silently deleting a draft is not the schema's call.)
CREATE UNIQUE INDEX IF NOT EXISTS kf_one_draft_per_article
    ON article_editions (article_id) WHERE status = 'draft';

INSERT INTO articles (id) VALUES (1) ON CONFLICT (id) DO NOTHING;
INSERT INTO article_editions (id, article_id) VALUES (1, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO article_editions (id, article_id) VALUES (2, 1) ON CONFLICT (id) DO NOTHING;

-- The tag vocabulary (read="public" write="none" — tag creation stays
-- out) and the join table the articles->tags edge introspects to. Never
-- a graph node.
CREATE TABLE IF NOT EXISTS tags (
    id   integer PRIMARY KEY,
    name text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS article_tags (
    article_id integer NOT NULL REFERENCES articles(id),
    tag_id     integer NOT NULL REFERENCES tags(id),
    PRIMARY KEY (article_id, tag_id)
);

INSERT INTO tags (id, name) VALUES
    (1, 'colonization'), (2, 'design'), (3, 'story'), (4, 'cycle'),
    (5, 'energy'), (6, 'water'), (7, 'air'), (8, 'food'),
    (9, 'materials'), (10, 'human')
ON CONFLICT (id) DO NOTHING;

-- Phase 9: comments (insert-only in the UI), owned by the commenter via
-- the direct users FK — comments hang off users in the graph, so the
-- owner walk is created_by, not the article's owner.
CREATE TABLE IF NOT EXISTS comments (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id integer NOT NULL REFERENCES article_editions(id),
    created_by integer REFERENCES users(id),
    body       text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Pro/con marks: insert-once by the UNIQUE (comment_id, user_id)
-- constraint, per RESOLVED (the KF v1.0 shape) — a second mark by the
-- same user is a database rejection answered 400, and changing a mark is
-- undesigned upsert territory, deliberately out. The surrogate id exists
-- because rows are id-addressable by framework contract (insert RETURNING
-- id, broadcasts carry id).
CREATE TABLE IF NOT EXISTS comment_marks (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id integer NOT NULL REFERENCES comments(id),
    user_id    integer NOT NULL REFERENCES users(id),
    kind       text NOT NULL CHECK (kind IN ('pro', 'con')),
    UNIQUE (comment_id, user_id)
);

-- Expositions: a rule-driven shelf of published articles. The rules are
-- ordinary rows an ordinary collection edits; the has-tag/lacks-tag SQL
-- lives in queries/expositionArticles.sql.
CREATE TABLE IF NOT EXISTS expositions (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_by  integer REFERENCES users(id),
    title       text NOT NULL DEFAULT '',
    description text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS exposition_tag_rules (
    id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exposition_id integer NOT NULL REFERENCES expositions(id) ON DELETE CASCADE,
    tag_id        integer NOT NULL REFERENCES tags(id),
    rule          text NOT NULL CHECK (rule IN ('has', 'lacks'))
);

-- Deleting an exposition takes its rules with it — the rules are the
-- exposition's definition, meaningless without it. Drop/re-add keeps the
-- upgrade idempotent for databases created before the cascade.
ALTER TABLE exposition_tag_rules DROP CONSTRAINT IF EXISTS exposition_tag_rules_exposition_id_fkey;
ALTER TABLE exposition_tag_rules ADD CONSTRAINT exposition_tag_rules_exposition_id_fkey
    FOREIGN KEY (exposition_id) REFERENCES expositions(id) ON DELETE CASCADE;
