-- The table exists and is named ONLY by the create action (no collection
-- binds it) — the create-declared insert target must still be startup-
-- validated. The action says "bodyy"; the column is "body".

CREATE TABLE IF NOT EXISTS cb_items (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body text NOT NULL DEFAULT ''
);
