-- The table exists; the arrow domain says "namee" where the column is
-- "name". Column existence is only startup-knowable, per the error
-- taxonomy — the LIMIT-0 probe must fail naming the site.

CREATE TABLE IF NOT EXISTS sb_tags (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL DEFAULT ''
);
