-- cu_items is owner-writable and reachable by the owner WALK (cu_items ->
-- cu_projects -> users), so reads and field writes would guard fine. But
-- it has no DIRECT users FK, so an INSERT cannot be ownership-stamped at
-- birth: by the unowned-denies floor the new row would be born unowned
-- and dead. The create action targeting it must be a startup error.

CREATE TABLE IF NOT EXISTS cu_projects (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(id),
    name    text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cu_items (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer REFERENCES cu_projects(id),
    body       text NOT NULL DEFAULT ''
);
