-- cu_items is owner-writable and owner-WALKABLE (cu_items -> cu_projects
-- -> users), so reads and field writes guard fine. But it has no direct
-- users FK to stamp, and the create action's columns (body) do not
-- include the walk's first hop column (project_id) — so no insert could
-- ever establish ownership: by the unowned-denies floor the new row
-- would be born unowned and dead. Per RESOLVED (ownership at birth may
-- arrive through the walk), THIS is the refined startup rejection — a
-- create action that did carry project_id would be legal, with the
-- server walking the referenced project's ownership at insert time.

CREATE TABLE IF NOT EXISTS cu_projects (
    id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id integer REFERENCES users(id),
    name    text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS cu_items (
    id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id integer REFERENCES cu_projects(id),
    body       text NOT NULL DEFAULT ''
);
