-- Phase 8 collection demo: a flat message board. The id is
-- server-assigned (identity column) — the insert path never takes one
-- from the client. No auth: tokenless end to end, Phase 4 style.

CREATE TABLE IF NOT EXISTS messages (
    id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    body text NOT NULL DEFAULT ''
);
